"""
One-call PEST++ setup from an IWFM model folder.

:func:`pest_setup_from_model` composes the package's verified building
blocks — ``open_model`` discovery, hydrograph linking,
:func:`~iwfm_io.pest.sim2obs.match_sim_to_obs` pairing,
:func:`~iwfm_io.pest.params.build_parameters` +
:class:`~iwfm_io.pest.apply.ApplyAction` multipliers, and the
:class:`~iwfm_io.pest.setup.PestSetup` capstone — into a runnable
pestpp-ies template directory:

- ``model/`` — a copy of the model (hardlinked where safe), the thing
  each forward run modifies and runs;
- multiplier templates/value files for the requested properties, zoned
  by subregion × layer (or per layer, or one global multiplier each);
- head observations paired to the model's own GW hydrograph outputs by
  hydrograph *name* (or id), interpolated to observation timestamps;
- a fail-fast forward run: apply parameters → run the IWFM executables
  → re-extract simulated values at the observation timestamps;
- the ``{case}.pst`` v2 control file wiring it all together.

The template scales out with
:func:`~iwfm_io.pest.orchestrate.setup_agents`, and results load back
with :func:`~iwfm_io.pest.ies.load_ies_ensembles`. The same entry point
backs the ``iwfm-io pest setup`` command line.

Requirements: the model must have been run once (the hydrograph output
file is how observations are paired), and observation site names must
match GW hydrograph names or ids from the GW main file.

Example::

    from iwfm_io.pest import pest_setup_from_model

    qs = pest_setup_from_model(
        "path/to/model", "obs_heads.smp", "pest_template",
        parameters=("kh", "ss", "sy"), ies_num_reals=50)
    print(qs.summary())
    # then: pestpp-ies pest_template/iwfm_cal.pst  (or iwfm-io pest run)
"""

from __future__ import annotations

import json
import logging
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

from iwfm_io._writer import replace_file_text

__all__ = ["pest_setup_from_model", "QuickstartSetup",
           "run_forward", "run_extract"]

logger = logging.getLogger(__name__)

CONFIG_FILE = "_quickstart.json"
OBS_INDEX_FILE = "_obs_index.csv"

#: default multiplier bounds per parameterizable property (log transform)
PROPERTY_BOUNDS = {
    "kh": (0.1, 10.0),
    "kv": (0.1, 10.0),
    "aquitard_kv": (0.1, 10.0),
    "ss": (0.1, 10.0),
    "sy": (0.5, 2.0),
    "strk": (0.01, 100.0),
}

_RUN_STEP = """\
# generated by iwfm_io.pest.quickstart — runs the IWFM executables
from iwfm_io.pest.quickstart import run_forward
run_forward()
"""

_EXTRACT_STEP = """\
# generated by iwfm_io.pest.quickstart — writes simulated observations
from iwfm_io.pest.quickstart import run_extract
run_extract()
"""


@dataclass
class QuickstartSetup:
    """Result of :func:`pest_setup_from_model`.

    Attributes
    ----------
    template : Path
        The written template directory (contains ``{case}.pst``).
    case : str
    paired : pandas.DataFrame
        The retained observations: ``site, datetime, observed,
        simulated, obsnme`` (simulated = the baseline run's values).
    par_data : pandas.DataFrame
        PEST++ v2 parameter-data rows.
    obs_data : pandas.DataFrame
        PEST++ v2 observation-data rows.
    dropped : pandas.DataFrame
        Observation rows excluded from the setup, with a ``reason``
        column (``no_hydrograph`` / ``no_simulated_value``).
    stats : pandas.DataFrame
        Baseline fit statistics per site (:func:`residual_stats`).
    """

    template: Path
    case: str
    paired: "pd.DataFrame"
    par_data: "pd.DataFrame"
    obs_data: "pd.DataFrame"
    dropped: "pd.DataFrame"
    stats: "pd.DataFrame"

    def summary(self) -> dict:
        out = {
            "template": str(self.template),
            "case": self.case,
            "n_parameters": int(len(self.par_data)),
            "parameter_groups": sorted(self.par_data["pargp"].unique()),
            "n_observations": int(len(self.obs_data)),
            "n_sites": int(self.paired["site"].nunique()),
            "n_dropped_observations": int(len(self.dropped)),
        }
        if len(self.dropped):
            out["dropped_reasons"] = (
                self.dropped["reason"].value_counts().to_dict())
        if len(self.stats):
            fit = self.stats.reset_index()
            keep = [c for c in ("site", "n", "rmse", "mean_res", "r2",
                                "nse") if c in fit.columns]
            out["baseline_fit"] = fit[keep].round(3).to_dict("records")
        return out


# ---------------------------------------------------------------- inputs
def _load_obs(obs, date_format: Optional[str]) -> "pd.DataFrame":
    """Accept a long-form frame, an SMP path, or a CSV path."""
    if isinstance(obs, pd.DataFrame):
        df = obs.copy()
    else:
        path = Path(obs)
        if not path.is_file():
            raise FileNotFoundError(f"observation file not found: {path}")
        if path.suffix.lower() == ".smp":
            from iwfm_io.pest.smp import read_smp
            df = read_smp(path, date_format=date_format)
        else:
            df = pd.read_csv(path)
    missing = {"site", "datetime", "value"} - set(df.columns)
    if missing:
        raise ValueError(
            f"observations need columns site, datetime, value "
            f"(missing: {sorted(missing)})")
    df = df.copy()
    df["site"] = df["site"].astype(str).str.strip()
    df["datetime"] = pd.to_datetime(df["datetime"])
    df["value"] = pd.to_numeric(df["value"], errors="coerce")
    n_nan = int(df["value"].isna().sum())
    if n_nan:
        logger.warning("dropping %d observation(s) with non-numeric "
                       "values", n_nan)
        df = df.dropna(subset=["value"])
    dup = df.duplicated(["site", "datetime"])
    if dup.any():
        logger.warning("averaging %d duplicate (site, datetime) "
                       "observation(s)", int(dup.sum()))
        df = (df.groupby(["site", "datetime"], as_index=False)["value"]
              .mean())
    if df.empty:
        raise ValueError("no usable observations")
    return df.sort_values(["site", "datetime"]).reset_index(drop=True)


def _match_sites(obs: "pd.DataFrame",
                 hydrographs: "pd.DataFrame") -> "Dict[str, int]":
    """Map observation site names to GW hydrograph ids.

    Matches case-insensitively on the hydrograph ``name`` column, then
    on the numeric ``id``. Returns ``{site: hyd_id}`` for matched sites.
    """
    by_key: Dict[str, int] = {}
    ids = pd.to_numeric(hydrographs["id"], errors="coerce")
    names = hydrographs.get("name")
    if names is not None:
        for name, hid in zip(names, ids):
            if pd.isna(hid) or name is None or str(name).strip() == "":
                continue
            key = str(name).strip().casefold()
            if key in by_key:
                logger.warning("duplicate hydrograph name %r — first "
                               "occurrence wins", str(name))
                continue
            by_key[key] = int(hid)
    for hid in ids.dropna():
        by_key.setdefault(str(int(hid)), int(hid))

    site_to_id = {}
    for site in obs["site"].unique():
        hid = by_key.get(str(site).casefold())
        if hid is not None:
            site_to_id[site] = hid
    return site_to_id


def _read_hydrograph_frame(path: Path) -> "pd.DataFrame":
    """Read a hydrograph output (.out text or .hdf) and normalize to a
    datetime-indexed frame with integer hydrograph-id columns."""
    from iwfm_io.wells import normalize_hydrograph_output
    if path.suffix.lower() in (".hdf", ".h5"):
        from iwfm_io.readers.hdf5 import read_hydrograph_hdf
        raw = read_hydrograph_hdf(path)
    else:
        from iwfm_io.readers.text_output import read_hydrograph_out
        raw = read_hydrograph_out(path)
    return normalize_hydrograph_output(raw)


def _find_hydrograph_output(declared: Path) -> Path:
    """The declared .out path, or its .hdf sibling as a fallback."""
    for cand in (declared, declared.with_suffix(".hdf"),
                 declared.with_suffix(".out")):
        if cand.is_file():
            return cand
    raise FileNotFoundError(
        f"GW hydrograph output not found ({declared} or an .hdf "
        f"sibling). Run the model once (iwfm_io.run_model) so the "
        f"hydrograph outputs exist before building the PEST setup.")


# ------------------------------------------------------------ parameters
def _gw_param_table(gw) -> "Tuple[str, pd.DataFrame, bool]":
    """The GW main's aquifer parameter table: (table_path, frame,
    is_parametric)."""
    if isinstance(gw.aquifer_params, pd.DataFrame):
        return "aquifer_params", gw.aquifer_params, False
    grids = [(i, g) for i, g in enumerate(gw.parametric_grids or [])
             if isinstance(g.get("params"), pd.DataFrame)]
    if len(grids) == 1:
        i, g = grids[0]
        return f"parametric_grids.{i}.params", g["params"], True
    if len(grids) > 1:
        raise NotImplementedError(
            f"GW main has {len(grids)} parametric grids; the quickstart "
            f"handles one. Build the setup with the full API "
            f"(ParamSpec/ApplyAction per grid table "
            f"'parametric_grids.<i>.params').")
    raise ValueError("GW main has no aquifer parameter table")


def _node_subregions(model) -> "pd.Series":
    """node_id → subregion (from element membership, first touch)."""
    elems = model.elements_df()
    node_cols = [c for c in elems.columns if re.match(r"^node\d+$", str(c))]
    long = elems.melt(id_vars=["subregion"], value_vars=node_cols,
                      value_name="node")[["node", "subregion"]]
    long["node"] = pd.to_numeric(long["node"], errors="coerce")
    long = long[long["node"].notna() & (long["node"] != 0)]
    return (long.drop_duplicates("node")
            .set_index(long.drop_duplicates("node")["node"].astype(int))
            ["subregion"])


def _zone_series(table, zones: str, model, parametric: bool):
    """Per-row zone labels for the parameter table (None = global)."""
    if zones == "global":
        return None
    layer = pd.to_numeric(table["layer"], errors="coerce").astype(int)
    if zones == "layer":
        return "l" + layer.astype(str)
    if zones != "subregion":
        raise ValueError(
            f"zones must be 'subregion', 'layer', or 'global', "
            f"got {zones!r}")
    node_sub = _node_subregions(model)
    if parametric:
        # parametric nodes have their own numbering — locate by x, y
        nodes = model.nodes_df()
        nx = nodes["x"].to_numpy(dtype=float)
        ny = nodes["y"].to_numpy(dtype=float)
        px = pd.to_numeric(table["x"], errors="coerce").to_numpy(dtype=float)
        py = pd.to_numeric(table["y"], errors="coerce").to_numpy(dtype=float)
        d2 = (px[:, None] - nx[None, :]) ** 2 + (py[:, None] - ny[None, :]) ** 2
        nearest = nodes["node_id"].to_numpy()[np.argmin(d2, axis=1)]
        sub = pd.Series(nearest, index=table.index).map(node_sub)
    else:
        sub = pd.to_numeric(table["node_id"], errors="coerce").astype(int) \
            .map(node_sub)
    if sub.isna().any():
        n = int(sub.isna().sum())
        logger.warning("%d parameter row(s) have no subregion — grouped "
                       "as zone 'sr0'", n)
        sub = sub.fillna(0)
    return ("sr" + sub.astype(int).astype(str)
            + "_l" + layer.astype(str))


def _build_parameter_specs(model, gw, sim, model_dir: Path,
                           sim_dir: Path, parameters: Sequence[str],
                           zones: str, bounds: Optional[Dict]):
    from iwfm_io.pest.apply import ApplyAction
    from iwfm_io.pest.params import ParamSpec

    limits = {**PROPERTY_BOUNDS, **(bounds or {})}
    # IWFM resolves referenced paths against the simulation working
    # directory — the writers must relativise against it on re-write
    sim_base = f"model/{sim_dir.relative_to(model_dir).as_posix()}"
    specs, actions = [], []
    gw_props = [p for p in parameters if p != "strk"]

    if gw_props:
        table_path, table, parametric = _gw_param_table(gw)
        missing = [p for p in gw_props if p not in table.columns]
        if missing:
            raise ValueError(
                f"GW parameter table has no column(s) {missing}; "
                f"available: {[c for c in table.columns if c not in ('node_id', 'x', 'y', 'layer')]}")
        zone = _zone_series(table, zones, model, parametric)
        gw_rel = Path(sim.file_paths["gw_main"]).resolve() \
            .relative_to(model_dir)
        for prop in gw_props:
            lo, hi = limits.get(prop, (0.1, 10.0))
            vfile = f"mult_{prop}.csv"
            keys = table[["node_id", "layer"]].copy()
            if zone is not None:
                keys["zone"] = zone.values
            specs.append(ParamSpec(
                name=prop, values_file=vfile, keys=keys,
                zone_col="zone" if zone is not None else None,
                transform="log", lower=lo, upper=hi, initial=1.0))
            actions.append(ApplyAction(
                reader="gw_main", path=f"model/{gw_rel.as_posix()}",
                table=table_path, column=prop, values_file=vfile,
                key_cols=("node_id", "layer"), op="multiply",
                base_dir=sim_base))

    if "strk" in parameters:
        stream = model._stream_main
        st_path = (sim.file_paths or {}).get("stream_main")
        if stream is None or st_path is None:
            raise ValueError(
                "model has no stream component — drop 'strk' from "
                "parameters")
        st_rel = Path(st_path).resolve().relative_to(model_dir)
        lo, hi = limits["strk"]
        specs.append(ParamSpec(
            name="strk", values_file="mult_strk.csv",
            keys=stream.reach_params[["reach_id"]].copy(),
            transform="log", lower=lo, upper=hi, initial=1.0))
        actions.append(ApplyAction(
            reader="stream_main", path=f"model/{st_rel.as_posix()}",
            table="reach_params", column="conductance",
            values_file="mult_strk.csv", key_cols=("reach_id",),
            op="multiply", base_dir=sim_base))

    if not specs:
        raise ValueError("parameters must name at least one property")
    return specs, actions


# ------------------------------------------------------------- the build
def pest_setup_from_model(model_dir, obs, dest_dir, case: str = "iwfm_cal",
                          parameters: Sequence[str] = ("kh",),
                          zones: str = "subregion",
                          bounds: Optional[Dict] = None,
                          date_format: Optional[str] = None,
                          max_gap="45D", weight: float = 1.0,
                          obs_group: str = "gwh", noptmax: int = 0,
                          ies_num_reals: Optional[int] = None,
                          pestpp_options: Optional[Dict] = None,
                          run_steps: Sequence[str] = ("preprocessor",
                                                      "simulation"),
                          python: Optional[str] = None,
                          link_model: bool = True,
                          overwrite: bool = False) -> QuickstartSetup:
    """Build a runnable pestpp-ies template directory from a model folder.

    Parameters
    ----------
    model_dir : path
        The model root (``Preprocessor/``, ``Simulation/``, ``Results/``,
        usually ``Bin/``). Must have been run at least once so the GW
        hydrograph output exists.
    obs : DataFrame or path
        Observed heads: long-form ``site, datetime, value``, an SMP
        file, or a CSV with those columns. Site names must match GW
        hydrograph names (or ids) from the GW main file.
    dest_dir : path
        Template directory to create.
    case : str
        Control-file stem.
    parameters : sequence of str
        Properties to parameterize as multipliers. GW aquifer columns
        (``kh, kv, aquitard_kv, ss, sy`` — whatever the model's table
        has) and/or ``strk`` (stream-reach conductance, one global
        multiplier applied per reach).
    zones : {"subregion", "layer", "global"}
        Multiplier granularity for the GW properties: one parameter per
        subregion × layer (default), per layer, or a single global one.
    bounds : dict, optional
        ``{property: (lower, upper)}`` multiplier-bound overrides
        (defaults in :data:`PROPERTY_BOUNDS`).
    date_format : str, optional
        Passed to :func:`read_smp` for SMP observation files.
    max_gap : str or Timedelta, optional
        Interpolation gap guard (see :func:`match_sim_to_obs`).
    weight : float
        Initial observation weight.
    obs_group : str
        Observation group / name prefix.
    noptmax, ies_num_reals, pestpp_options
        Control settings; ``noptmax=0`` (default) makes the first run a
        cheap single-forward-run check.
    run_steps : sequence of str
        IWFM tools the forward run executes (see :func:`run_model`).
    python : str, optional
        Interpreter for the forward-run steps (default: the current
        one).
    link_model : bool
        Hardlink unchanged model files into the template (fast,
        near-zero disk; falls back to copying across volumes).
    overwrite : bool
        Replace an existing ``dest_dir/model`` copy.

    Returns
    -------
    QuickstartSetup
    """
    from iwfm_io.model_adapter import open_model
    from iwfm_io.pest.names import encode_obs_names
    from iwfm_io.pest.obsfiles import ObsFileSpec
    from iwfm_io.pest.params import build_parameters
    from iwfm_io.pest.budget_obs import slugify_label
    from iwfm_io.pest.setup import PestSetup
    from iwfm_io.pest.sim2obs import match_sim_to_obs
    from iwfm_io.pest.stats import residual_stats
    from iwfm_io.scenario import create_scenario

    model_dir = Path(model_dir).resolve()
    dest = Path(dest_dir)
    model = open_model(model_dir)
    sim, gw = model._sim, model._gw_main
    if sim is None:
        raise ValueError(f"could not locate/parse a simulation main "
                         f"file under {model_dir}")
    if gw is None:
        raise ValueError("could not parse the groundwater main file "
                         "(referenced by the simulation main)")
    if gw.hydrographs is None or not len(gw.hydrographs):
        raise ValueError("the GW main defines no hydrograph outputs — "
                         "the quickstart pairs observations against "
                         "them; add hydrograph locations first")
    if gw.hydrograph_out_file is None:
        raise ValueError("the GW main defines no hydrograph output file")

    # --- observations: match sites, pair against the baseline run
    obs_df = _load_obs(obs, date_format)
    site_to_id = _match_sites(obs_df, gw.hydrographs)
    matched = obs_df["site"].isin(site_to_id)
    dropped_frames = []
    if (~matched).any():
        d = obs_df[~matched].copy()
        d["reason"] = "no_hydrograph"
        dropped_frames.append(d)
        logger.warning(
            "%d observation(s) at %d site(s) match no GW hydrograph "
            "name/id and are dropped, e.g. %s", len(d),
            d["site"].nunique(), sorted(d["site"].unique())[:5])
    obs_df = obs_df[matched]
    if obs_df.empty:
        names = [str(n) for n in gw.hydrographs.get(
            "name", pd.Series(dtype=object)).dropna()]
        raise ValueError(
            f"no observation site matches a GW hydrograph name/id; "
            f"hydrograph names look like: {names[:8]}")

    declared_out = Path(gw.hydrograph_out_file).resolve()
    hyd_path = _find_hydrograph_output(declared_out)
    hyd = _read_hydrograph_frame(hyd_path)
    id_of = {s: i for s, i in site_to_id.items()}
    missing_cols = sorted({i for i in id_of.values()} - set(hyd.columns))
    if missing_cols:
        raise ValueError(
            f"hydrograph output {hyd_path.name} lacks column(s) for "
            f"hydrograph id(s) {missing_cols[:5]}")
    sim_by_site = pd.DataFrame(
        {site: hyd[hid] for site, hid in id_of.items()}, index=hyd.index)

    paired = match_sim_to_obs(sim_by_site, obs_df, max_gap=max_gap)
    unfilled = paired["simulated"].isna()
    if unfilled.any():
        d = paired[unfilled].rename(columns={"observed": "value"})[
            ["site", "datetime", "value"]].copy()
        d["reason"] = "no_simulated_value"
        dropped_frames.append(d)
        logger.warning("%d observation(s) fall outside the simulated "
                       "period/gap guard and are dropped",
                       int(unfilled.sum()))
        paired = paired[~unfilled]
    if paired.empty:
        raise ValueError("no observation could be paired with the "
                         "simulated period — check dates/date_format")
    paired = paired.reset_index(drop=True)
    paired["obsnme"] = encode_obs_names(
        obs_group, paired["site"].map(slugify_label), paired["datetime"])
    dup = paired["obsnme"].duplicated()
    if dup.any():
        raise ValueError(
            f"duplicate observation name(s) after encoding, e.g. "
            f"{sorted(paired.loc[dup, 'obsnme'].unique())[:3]} — site "
            f"names collide once slugified")
    dropped = (pd.concat(dropped_frames, ignore_index=True)
               if dropped_frames else
               pd.DataFrame(columns=["site", "datetime", "value",
                                     "reason"]))

    # --- parameters
    from iwfm_io.model_adapter import _find_simulation_main
    sim_main = _find_simulation_main(model_dir)
    if sim_main is None:
        raise ValueError(f"could not locate the simulation main file "
                         f"under {model_dir}")
    sim_dir = Path(sim_main).resolve().parent
    specs, actions = _build_parameter_specs(
        model, gw, sim, model_dir, sim_dir, parameters, zones, bounds)
    bundle = build_parameters(specs)

    # --- assemble the template
    spec = ObsFileSpec(list(paired["obsnme"]))
    obs_data = spec.obs_data(
        values=pd.Series(paired["observed"].to_numpy(),
                         index=paired["obsnme"]),
        weight=weight, group=obs_group)
    output_file = f"{case}_heads.pout"
    py = python or sys.executable

    s = PestSetup(case)
    s.add_parameters(bundle, actions=actions)
    s.add_observations(obs_data, spec, output_file=output_file)
    s.add_run_step("run iwfm", f'"{py}" _run_step.py')
    s.add_run_step("extract observations", f'"{py}" _extract_step.py')
    s.control_data["noptmax"] = noptmax
    if ies_num_reals is not None:
        s.pestpp_options["ies_num_reals"] = ies_num_reals
    s.pestpp_options.update(pestpp_options or {})
    s.write(dest)

    replace_file_text(dest / "_run_step.py", _RUN_STEP, encoding="utf-8")
    replace_file_text(dest / "_extract_step.py", _EXTRACT_STEP,
                      encoding="utf-8")
    obs_index = paired[["obsnme", "site", "datetime"]].copy()
    obs_index["hyd_id"] = obs_index["site"].map(site_to_id)
    replace_file_text(dest / OBS_INDEX_FILE, obs_index.to_csv(index=False))
    hyd_rel = declared_out.relative_to(model_dir)
    config = {
        "case": case,
        "model_dir": "model",
        "run_steps": list(run_steps),
        "hyd_file": f"model/{hyd_rel.as_posix()}",
        "obs_index": OBS_INDEX_FILE,
        "output_file": output_file,
        "max_gap": None if max_gap is None else str(max_gap),
    }
    replace_file_text(dest / CONFIG_FILE, json.dumps(config, indent=1))

    # the model copy each forward run modifies and runs
    create_scenario(model_dir, dest / "model",
                    link_unchanged=link_model, overwrite=overwrite)

    stats = residual_stats(paired, by="site")
    result = QuickstartSetup(
        template=dest, case=case, paired=paired,
        par_data=bundle.par_data, obs_data=obs_data, dropped=dropped,
        stats=stats)
    logger.info(
        "quickstart: %s — %d parameter(s), %d observation(s) at %d "
        "site(s), %d dropped", dest / f"{case}.pst",
        len(bundle.par_data), len(obs_data), paired["site"].nunique(),
        len(dropped))
    return result


# ---------------------------------------------------------- forward run
def run_forward(config: str = CONFIG_FILE) -> None:
    """Forward-run step: run the IWFM executables on the template's
    model copy (invoked by the generated ``_run_step.py``)."""
    from iwfm_io.run import run_model
    cfg = json.loads(Path(config).read_text())
    run_model(cfg["model_dir"], steps=tuple(cfg["run_steps"]))


def run_extract(config: str = CONFIG_FILE) -> None:
    """Forward-run step: interpolate the fresh hydrograph output to the
    observation timestamps and write the PEST output file (invoked by
    the generated ``_extract_step.py``).

    Uses the same observation index, interpolation settings, and
    output-file spec the setup wrote — so the output always matches the
    instruction file. A missing simulated value raises (fail fast)
    rather than feeding PEST a stale or misaligned number.
    """
    from iwfm_io.pest.obsfiles import ObsFileSpec
    from iwfm_io.pest.sim2obs import match_sim_to_obs

    cfg = json.loads(Path(config).read_text())
    idx = pd.read_csv(cfg["obs_index"], parse_dates=["datetime"])
    idx["site"] = idx["site"].astype(str)
    hyd_path = _find_hydrograph_output(Path(cfg["hyd_file"]))
    hyd = _read_hydrograph_frame(hyd_path)

    pairs = idx[["site", "hyd_id"]].drop_duplicates()
    missing = sorted(set(pairs["hyd_id"].astype(int))
                     - set(int(c) for c in hyd.columns))
    if missing:
        raise ValueError(
            f"hydrograph output {hyd_path} lacks id(s) {missing[:5]}")
    sim_by_site = pd.DataFrame(
        {site: hyd[int(hid)] for site, hid
         in zip(pairs["site"], pairs["hyd_id"])}, index=hyd.index)

    obs_stub = idx[["site", "datetime"]].assign(value=0.0)
    paired = match_sim_to_obs(sim_by_site, obs_stub,
                              max_gap=cfg.get("max_gap"))
    merged = idx.merge(paired[["site", "datetime", "simulated"]],
                       on=["site", "datetime"], how="left")
    ObsFileSpec(list(idx["obsnme"])).write_output(
        pd.Series(merged["simulated"].to_numpy(),
                  index=merged["obsnme"]),
        cfg["output_file"])
