"""
PestSetup: assemble a complete, runnable PEST++ interface.

The capstone of ``iwfm_io.pest``: accumulate parameters (built with
:func:`~iwfm_io.pest.params.build_parameters`, applied with
:class:`~iwfm_io.pest.apply.ApplyAction`), observations (named tables +
:class:`~iwfm_io.pest.obsfiles.ObsFileSpec` paired writers), and the
model run steps — then :meth:`PestSetup.write` emits a coherent
template directory:

- every template + initial value file, every instruction file;
- ``{case}_par_data.csv`` / ``{case}_pargp_data.csv`` /
  ``{case}_obs_data.csv`` (PEST++ v2 external tables);
- a generated fail-fast ``forward_run.py`` whose first step applies the
  PEST-written value files onto the model inputs
  (:func:`~iwfm_io.pest.apply.apply_parameters`) and whose remaining
  steps are the model run and observation extraction;
- the ``{case}.pst`` version-2 control file wiring it all together.

The result runs directly under ``pestpp-ies`` (or glm/sen/…), scales
out with :func:`~iwfm_io.pest.orchestrate.setup_agents`, and its
outputs load back with
:func:`~iwfm_io.pest.ies.load_ies_ensembles`.

Example::

    s = PestSetup("demo")
    s.add_parameters(bundle, actions=[...])
    s.add_observations(obs_df, spec, output_file="obs_out.csv")
    s.add_run_step("model", "python run_model.py")
    s.control_data["noptmax"] = 0
    s.pestpp_options["ies_num_reals"] = 30
    s.write("template/")
"""

from __future__ import annotations

import json
import sys
import logging
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence

import pandas as pd

from iwfm_io._writer import replace_file_text
from iwfm_io.pest.apply import ApplyAction
from iwfm_io.pest.obsfiles import ObsFileSpec
from iwfm_io.pest.orchestrate import write_forward_run
from iwfm_io.pest.params import ParamBundle

__all__ = ["PestSetup"]

logger = logging.getLogger(__name__)

_APPLY_STEP = """\
# -*- coding: utf-8 -*-
# generated by iwfm_io.pest.PestSetup - applies PEST value files
import json, sys
from iwfm_io.pest.apply import ApplyAction, apply_parameters
with open("_apply_actions.json") as f:
    actions = [ApplyAction(**a) for a in json.load(f)]
apply_parameters(".", actions)
"""


@dataclass
class _ObsBlock:
    obs_data: "pd.DataFrame"
    spec: ObsFileSpec
    output_file: str
    ins_file: str


class PestSetup:
    """Builder for a runnable PEST++ v2 template directory.

    Parameters
    ----------
    case : str
        Control-file stem (``{case}.pst``).
    command : str, optional
        Model command line (default: the generated
        ``python forward_run.py``).
    """

    def __init__(self, case: str = "case", command: Optional[str] = None,
                 python: Optional[str] = None):
        self.case = case
        self.command = command
        #: interpreter used for the generated run steps (default: the
        #: one building the template, so agents never depend on PATH)
        self.python = python or sys.executable
        self.control_data: Dict = {"pestmode": "estimation", "noptmax": 0}
        self.pestpp_options: Dict = {}
        self._bundles: List[ParamBundle] = []
        self._actions: List[ApplyAction] = []
        self._obs: List[_ObsBlock] = []
        self._steps: List = []

    # ------------------------------------------------------------ builders
    def add_parameters(self, bundle: ParamBundle,
                       actions: Sequence[ApplyAction] = ()) -> "PestSetup":
        """Add a parameter bundle and the apply actions that consume its
        value files in the forward run."""
        bundle.verify()
        for a in actions:
            files = {f[:-len(".tpl")] for f in bundle.tpl_texts}
            if a.values_file not in files:
                logger.warning(
                    "action for %s does not match any value file of this "
                    "bundle (%s)", a.values_file, sorted(files))
        self._bundles.append(bundle)
        self._actions.extend(actions)
        return self

    def add_observations(self, obs_data, spec: ObsFileSpec,
                         output_file: str,
                         ins_file: Optional[str] = None) -> "PestSetup":
        """Add observations: the v2 obs-data rows plus the paired
        output/instruction spec.

        Parameters
        ----------
        obs_data : pandas.DataFrame
            ``obsnme, obsval, weight, obgnme`` rows (e.g.
            ``spec.obs_data(...)`` or any pest-module observation
            table joined to observed values).
        spec : ObsFileSpec
        output_file : str
            The model-output file a forward-run step writes (via
            ``spec.write_output``).
        ins_file : str, optional
            Instruction file name (default ``{output_file}.ins``).
        """
        required = {"obsnme", "obsval", "weight", "obgnme"}
        if not required <= set(obs_data.columns):
            raise ValueError(f"obs_data needs columns {sorted(required)}")
        names_df = set(obs_data["obsnme"].astype(str))
        names_spec = set(spec.names)
        if names_df != names_spec:
            raise ValueError(
                f"obs_data and spec name mismatch: "
                f"{len(names_df ^ names_spec)} difference(s), e.g. "
                f"{sorted(names_df ^ names_spec)[:3]}")
        self._obs.append(_ObsBlock(
            obs_data=obs_data.copy(), spec=spec, output_file=output_file,
            ins_file=ins_file or f"{output_file}.ins"))
        return self

    def add_run_step(self, label: str, command: str) -> "PestSetup":
        """Append a forward-run step (model run, extraction, …)."""
        self._steps.append((label, command))
        return self

    # --------------------------------------------------------------- write
    def write(self, dest_dir) -> Path:
        """Write the complete template directory; returns its path."""
        if not self._bundles:
            raise ValueError("no parameters added")
        if not self._obs:
            raise ValueError("no observations added")
        if not self._steps and self.command is None:
            raise ValueError(
                "no run steps added — the forward run would produce no "
                "model outputs")
        dest = Path(dest_dir)
        dest.mkdir(parents=True, exist_ok=True)

        # parameters
        par = pd.concat([b.par_data for b in self._bundles],
                        ignore_index=True)
        dup = par["parnme"][par["parnme"].duplicated()]
        if len(dup):
            raise ValueError(
                f"duplicate parameter name(s) across bundles: "
                f"{sorted(dup.unique())[:5]}")
        pargp = (pd.concat([b.pargp_data for b in self._bundles],
                           ignore_index=True)
                 .drop_duplicates("pargpnme"))
        for b in self._bundles:
            b.write(dest)

        # observations
        obs = pd.concat([o.obs_data for o in self._obs], ignore_index=True)
        dup = obs["obsnme"][obs["obsnme"].duplicated()]
        if len(dup):
            raise ValueError(
                f"duplicate observation name(s): {sorted(dup.unique())[:3]}")
        outputs = [o.output_file for o in self._obs]
        dup_out = {f for f in outputs if outputs.count(f) > 1}
        if dup_out:
            raise ValueError(
                f"observation blocks share output file(s) {sorted(dup_out)} "
                "— each block needs its own model output file, otherwise "
                "their instruction files overwrite each other")
        for o in self._obs:
            o.spec.write_ins(dest / o.ins_file)

        # external tables
        par_csv = f"{self.case}_par_data.csv"
        pargp_csv = f"{self.case}_pargp_data.csv"
        obs_csv = f"{self.case}_obs_data.csv"
        replace_file_text(dest / par_csv, par.to_csv(index=False))
        replace_file_text(dest / pargp_csv, pargp.to_csv(index=False))
        replace_file_text(dest / obs_csv, obs.to_csv(index=False))

        # forward run: apply step first, then user steps
        steps = []
        if self._actions:
            replace_file_text(dest / "_apply_actions.json",
                              json.dumps([asdict(a) for a in self._actions],
                                         indent=1))
            replace_file_text(dest / "_apply_step.py", _APPLY_STEP,
                              encoding="utf-8")
            steps.append(("apply parameters",
                          f'"{self.python}" _apply_step.py'))
            # pristine snapshots: the apply step parameterises these,
            # never the live (already multiplied) files
            from iwfm_io.pest.apply import ensure_pristine
            for a in self._actions:
                target = dest / a.path
                if target.is_file():
                    ensure_pristine(target, warn=False)
        steps.extend(self._steps)
        if steps:
            write_forward_run(dest / "forward_run.py", steps)
        command = self.command or f'"{self.python}" forward_run.py'

        # control file
        clash = set(self.control_data) & set(self.pestpp_options)
        if clash:
            raise ValueError(
                f"keyword(s) {sorted(clash)} set in both control_data and "
                "pestpp_options — decide which value applies")
        lines = ["pcf version=2", "* control data keyword"]
        for k, v in {**self.control_data, **self.pestpp_options}.items():
            if v is None:
                raise ValueError(f"control keyword {k!r} is None")
            lines.append(f"{k:<30} {v}")
        lines += ["* parameter groups external", pargp_csv,
                  "* parameter data external", par_csv,
                  "* observation data external", obs_csv,
                  "* model command line", command,
                  "* model input"]
        for b in self._bundles:
            for tpl_name in b.tpl_texts:
                lines.append(f"{tpl_name}  {tpl_name[:-len('.tpl')]}")
        lines.append("* model output")
        for o in self._obs:
            lines.append(f"{o.ins_file}  {o.output_file}")
        replace_file_text(dest / f"{self.case}.pst",
                          "\n".join(lines) + "\n")
        logger.info(
            "PestSetup: wrote %s (%d parameters, %d observations, "
            "%d run step(s))", dest / f"{self.case}.pst", len(par),
            len(obs), len(steps))
        return dest
